brew "vips"
brew "libraw"
brew "exiftool"
brew "poppler"
brew "tesseract"
brew "tesseract-lang"
brew "ffmpeg"
brew "whisper-cpp"
brew "libyaml"
brew "postgresql@17"
brew "shellcheck"
brew "shfmt"
brew "ollama"

cask "chromium"
cask "libreoffice"
cask "font-urw-base35"
