default: &default
  adapter: postgresql
  encoding: unicode
  gssencmode: disable
  pool: <%= [ ENV["RAILS_MAX_THREADS"].to_i, ENV.fetch("ANALYSIS_THREADS", 4).to_i + 5 ].max %>

development:
  primary: &primary_development
    <<: *default
    database: xixo_development
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USER", "xixo") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "xixo") %>
  cache:
    <<: *primary_development
    database: xixo_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: xixo_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: xixo_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *primary_development
    database: xixo_test
  cache:
    <<: *primary_development
    database: xixo_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: xixo_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: xixo_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: xixo_production
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: xixo
    password: <%= ENV["XIXO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: xixo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: xixo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: xixo_production_cable
    migrations_paths: db/cable_migrate
