default: &default
  adapter: postgresql
  encoding: unicode
  gssencmode: disable
  pool: <%= [ ENV["RAILS_MAX_THREADS"].to_i, ENV.fetch("ANALYSIS_THREADS", 4).to_i * (ENV.fetch("URIS_SCOUTS_AT_ONCE", 2).to_i.clamp(1, 6) + 1) + 5 ].max %>

development:
  primary: &primary_development
    <<: *default
    database: uris_development
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USER", "uris") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "uris") %>
  cache:
    <<: *primary_development
    database: uris_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: uris_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: uris_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *primary_development
    database: uris_test
  cache:
    <<: *primary_development
    database: uris_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: uris_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: uris_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: uris_production
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: uris
    password: <%= ENV["URIS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: uris_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: uris_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: uris_production_cable
    migrations_paths: db/cable_migrate
