uris_image: ghcr.io/urisrb/uris
uris_image_tag: latest
uris_image_digest: ""

uris_deploy_path: /srv/uris
uris_filesystem_root: /data/files
uris_network: edge

uris_postgres_host: postgres
uris_postgres_port: 5432
uris_postgres_user: uris

uris_opensearch_image: opensearchproject/opensearch:2.11.0
uris_opensearch_heap: 512m
uris_opensearch_memory: 1500m

uris_s3_image: cgr.dev/chainguard/minio@sha256:6a1d0b45c8669726bba580ced0bfa4cb9fdeed1ed636dfabd81d1577beb6937b
uris_s3_region: us-east-1
uris_s3_access_key_id: uris

uris_web_concurrency: 1
uris_max_threads: 3
uris_log_level: info
uris_analysis_concurrency: 1
uris_bulk_concurrency: 2
